### ISSUE TITLE
MailChimp Proxy

### ISSUE THREAD

**Issue by nerik** [Vizzuality/trase-api#33]
I set up a Mailchimp test account, see Slack convo.

Create an API endpoint that takes an email as a parameter and sends a query to the MailChimp API.

Endpoint is `https://us16.api.mailchimp.com/3.0/lists/{listId}/members/`
JSON Payload: 
```
{
    "email_address": "...",
    "status": "pending"
}
```

Auth by basic auth (API key as password) or OAuth2

Ref.
http://developer.mailchimp.com/documentation/mailchimp/guides/manage-subscribers-with-the-mailchimp-api/

**Comment by agnessa** [comment]
https://github.com/Vizzuality/trase-api/pull/46
