### ISSUE TITLE
Indonesian geoIDs / isGeo

### ISSUE THREAD

**Issue by nerik** [Vizzuality/trase-api#35]
- geoIds are missing from Indonesian Ports nodes in get_all_nodes (Clement said they are in the DB)
- isGeo not set to true on ports column in http://staging.trase.earth/api/v2/get_columns?&context_id=7 (easy hack on the frontend)

**Comment by agnessa** [comment]
I recall we fixed the second part of this, is the first one still an issue or maybe it fixed itself along the way? <wishful thinking in action>

**Comment by agnessa** [comment]
Assuming fixed.
